"""
Pad Translations for Drum Rack (pad_x, pad_y, note, channel)
"""
PAD_FEEDBACK_CHANNEL = 14
FEEDBACK_CHANNELS = range(5, 15) 
NON_FEEDBACK_CHANNEL = 15
PAD_TRANSLATIONS = (
 (0, 0, 60, PAD_FEEDBACK_CHANNEL),
 (1, 0, 61, PAD_FEEDBACK_CHANNEL),
 (2, 0, 62, PAD_FEEDBACK_CHANNEL),
 (3, 0, 63, PAD_FEEDBACK_CHANNEL),
 (0, 1, 52, PAD_FEEDBACK_CHANNEL),
 (1, 1, 53, PAD_FEEDBACK_CHANNEL),
 (2, 1, 54, PAD_FEEDBACK_CHANNEL),
 (3, 1, 55, PAD_FEEDBACK_CHANNEL),
 (0, 2, 44, PAD_FEEDBACK_CHANNEL),
 (1, 2, 45, PAD_FEEDBACK_CHANNEL),
 (2, 2, 46, PAD_FEEDBACK_CHANNEL),
 (3, 2, 47, PAD_FEEDBACK_CHANNEL),
 (0, 3, 36, PAD_FEEDBACK_CHANNEL),
 (1, 3, 37, PAD_FEEDBACK_CHANNEL),
 (2, 3, 38, PAD_FEEDBACK_CHANNEL),
 (3, 3, 39, PAD_FEEDBACK_CHANNEL))

